### ISSUE TITLE
The plugin does not work for me!

### ISSUE THREAD

**Issue by AugiTheEye** [Andicraft/stairs-character#1]
Hello Andicraft, I would like to report, that this plugin unfortunately isn't working for me. This error popped up when I tried to test it. Could you please check if it is fixable? I am using this on Godot 4.1.2 (stable)
![image](https://github.com/Andicraft/stairs-character/assets/148721140/df3c22bd-f7ed-4cdd-b527-83d24cfac351)

**Comment by Andicraft** [comment]
Hi! Yes - the base code won't work with Convex Polyon colliders. You'll want to use a mathematically defined a collider like a capsule, or otherwise you will have to replace `col_shape.height` with an exported variable so you can enter the height of your collider manually.

**Comment by AugiTheEye** [comment]
I do not know why, but when I use a Capsule it just says "Breakpoint" and it does not work. And if I put in a manual height, the Player does not climb the stairs
