### ISSUE TITLE
Invalid operands 'Vector3' and 'float' in operator '+'.

### ISSUE THREAD

**Issue by BananaHolograma** [Andicraft/stairs-character#2]
Hi, the following part of the code gives me the error that I wrote in the title:
```py
var dir = (local_pos * Vector3(1,0,1)).normalized()

local_pos += dir + step_margin # <<<<<<< This one

local_pos = local_pos.limit_length(_collider_radius + step_margin)
local_pos.y = _ray_shape_local_height
```

I think it should be a multiplication ` local_pos += dir * step_margin`

I didn't make a PR because I didn't know if it was really the initial intention.

Cheers!

**Comment by Andicraft** [comment]
Ah yes - that is indeed a typo, from me translating the code from C#. I’ll upload a fix ASAP.
