### ISSUE TITLE
Error when try to execute the game

### ISSUE THREAD

**Issue by Firezac** [Andicraft/stairs-character#3]
Hi!
I tried to add the plugin on my Godot project and I did as the orientation, changed the extends to StairCharacter and the handled_stairs() before the move_and_slide(), but every time I execute my game, this error happens:
<img width="951" alt="image" src="https://github.com/Andicraft/stairs-character/assets/9053366/e3fe1b56-24ea-4cfe-b47c-85bab23f3af4">
It is happening on the addon scripting and I try a bit but I don't know so much what I can do.
I am using Godot 4.1.2

**Comment by niceandgoodonline** [comment]
Since you need the _ready() of `StairsCharacter` to run to bootstrap the raycast/extra collider you need to call `super()` in the `_ready()` of your character controller script that inherits from `StairsCharacter`

**Comment by Firezac** [comment]
Now it works really fine. Thank you so much!!!!! :D
